// One-off: pulls the U-mark geometry out of the original prototype SVG
// and writes it as plain data for the Three.js scene.
import fs from 'node:fs';
const html = fs.readFileSync(new URL('../../unizova (3).html', import.meta.url), 'utf8');
const symStart = html.indexOf('<symbol id="umark"');
const sym = html.slice(symStart, html.indexOf('</symbol>', symStart));
const sprite = html.slice(html.indexOf('<svg width="0"'), html.indexOf('</svg>', html.indexOf('<symbol id="ic"')) + 6);
fs.writeFileSync(new URL('../src/assets/sprite.svg', import.meta.url), sprite);

const num = s => +(+s).toFixed(1);
const attr = (tag, n) => { const m = tag.match(new RegExp(`[ ]${n}="([^"]*)"`)); return m ? m[1] : null; };
const uPath = sym.match(/<clipPath id="cu"><path d="([^"]+)"/)[1];
const fPath = sym.match(/<clipPath id="cf"><path d="([^"]+)"/)[1];
const pts = d => d.replace(/[MLZ]/g, ' ').trim().split(/\s+/).map(p => p.split(',').map(num));

const facets = [...sym.matchAll(/<polygon[^>]*>/g)].map(([t]) => {
  const p = attr(t, 'points').split(/\s+/).flatMap(p => p.split(',').map(num));
  return [...p, +attr(t, 'fill-opacity')];
});
const lines = [...sym.matchAll(/<line[^>]*>/g)].map(([t]) =>
  [num(attr(t, 'x1')), num(attr(t, 'y1')), num(attr(t, 'x2')), num(attr(t, 'y2')), attr(t, 'stroke-dasharray') ? 1 : 0]);
const dust = [], nodes = [];
for (const m of sym.matchAll(/<circle([^>]*)>(<animate[^>]*\/>)?/g)) {
  const t = m[0], c = [num(attr(t, 'cx')), num(attr(t, 'cy')), num(attr(t, 'r'))];
  if (t.includes('url(#ng)')) {
    const a = m[2];
    nodes.push(a ? [...c, parseFloat(attr(a, 'dur')), parseFloat(attr(a, 'begin'))] : [...c, 0, 0]);
  } else dust.push([...c, +(attr(t, 'opacity') ?? 1)]);
}
const out = `// Generated by scripts/extract-mark.mjs from the original prototype SVG (viewBox 40 110 680 640).
export const U_OUTLINE = ${JSON.stringify(pts(uPath))};
export const FLAG_OUTLINE = ${JSON.stringify(pts(fPath))};
// [x1,y1,x2,y2,x3,y3,opacity]
export const FACETS = ${JSON.stringify(facets)};
// [x1,y1,x2,y2,dashed]
export const LINES = ${JSON.stringify(lines)};
// [cx,cy,r,opacity]
export const DUST = ${JSON.stringify(dust)};
// [cx,cy,r,twinkleDur,twinkleBegin] (dur 0 = steady)
export const NODES = ${JSON.stringify(nodes)};
`;
fs.writeFileSync(new URL('../src/components/umarkData.js', import.meta.url), out);
console.log({ facets: facets.length, lines: lines.length, dust: dust.length, nodes: nodes.length, sprite: sprite.length });
